
coverage:
  status:
    project:
      default:
        target: auto
      method:
        target: auto
        flags:
          - method
      unit:
        target: auto
        flags:
          - unit

flags:
  method:
    paths:
      - cclib/method
    carryforward: true
  unit:
    paths:
      - cclib/io
      - cclib/parser
      - cclib/bridge
    carryforward: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  
  show_carryforward_flags: true
