
coverage:
  status:
    project:
      default:
        target: auto
      method:
        target: auto
        flags:
          paths:
            - method
      unit:
        target: auto
      flag_coverage_not_uploaded_behavior: pass 
flags:
  method:
    paths:
      - cclib/method/
    carryforward: true
  unit:
    paths:
      - cclib/io/
      - cclib/parser/
      - cclib/bridge/
    carryforward: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: yes
  require_head: yes       
  branches: null
  show_carryforward_flags: true
