#!/usr/bin/env python
import os
import sys
import glob
import getopt
import logging

import numpy

from cclib.parser import ccopen
from cclib.method import CDA


if __name__ == "__main__":

    parser1 = ccopen(sys.argv[1], None, logging.ERROR)
    parser2 = ccopen(sys.argv[2], None, logging.ERROR)
    parser3 = ccopen(sys.argv[3], None, logging.ERROR)

    parser1.parse(); parser2.parse(); parser3.parse()
    fa = CDA(parser1, None, logging.ERROR)
    retval = fa.calculate([parser2, parser3])

    if retval:

        print "Charge decomposition analysis of %s\n"%(sys.argv[1])

        if len(parser1.homos) == 2:
            print "ALPHA SPIN:"
            print "==========="

        print " MO#      d       b       r"
        print "-----------------------------"

        for spin in range(len(parser1.homos)):

            if spin == 1:
                print "\nBETA SPIN:"
                print "=========="

            for i in range(len(fa.donations[spin])):

                print "%4i: %7.3f %7.3f %7.3f"%(i+1,fa.donations[spin][i], \
                                                    fa.bdonations[spin][i], \
                                                    fa.repulsions[spin][i])

                if i == parser1.homos[spin]:
                    print "------ HOMO - LUMO gap ------"
                    

            print "-----------------------------"
            print " T:   %7.3f %7.3f %7.3f"%(reduce(numpy.add, fa.donations[spin]), \
                        reduce(numpy.add, fa.bdonations[spin]), \
                        reduce(numpy.add, fa.repulsions[spin]))


