#!/usr/bin/env python

import sys
import os

if len(sys.argv) == 2:
    mfile = sys.argv[1] + ".out"
else:
    mfile = "turbo.out"

file = open(mfile,"w")
file.write("#CCLIB Turbomole\n")

if os.path.exists("basis"):
    file.write("#CCLIB basis\n")
    bfile = open("basis","r")
    data = bfile.read()
    file.write(data)
    bfile.close()

if os.path.exists("control"):
    file.write("#CCLIB control\n")
    bfile = open("control","r")
    data = bfile.read()
    file.write(data)
    bfile.close()

if os.path.exists("job.last"):
    file.write("#CCLIB job.last\n")
    bfile = open("job.last","r")
    data = bfile.read()
    file.write(data)
    bfile.close()

if os.path.exists("coord"):
    file.write("#CCLIB coord\n")
    bfile = open("coord","r")
    data = bfile.read()
    file.write(data)
    bfile.close()

if os.path.exists("gradient"):
    file.write("#CCLIB gradient\n")
    bfile = open("gradient","r")
    data = bfile.read()
    file.write(data)
    bfile.close()


if os.path.exists("mos"):
    file.write("#CCLIB mos\n")
    bfile = open("mos","r")
    data = bfile.read()
    file.write(data)
    bfile.close()

if os.path.exists("alpha") and os.path.exists("beta"):
    file.write("#CCLIB mos\n")
    bfile = open("alpha","r")
    data = bfile.read()
    file.write(data)
    bfile.close()

    bfile = open("beta","r")
    data = bfile.read()
    file.write(data)
    bfile.close()

if os.path.exists("aoforce.out"):
    file.write("#CCLIB aoforce.out\n")
    bfile = open("aoforce.out","r")
    data = bfile.read()
    file.write(data)
    bfile.close()

#eof
