from dataclasses import dataclass

import cclib.parser_properties as cprops


@dataclass
class combinator:
    name: str
    job_list: list


DEFAULT_PARSERS = [
    cprops.scfenergies,
    cprops.atomcoords,
    cprops.atomnos,
    cprops.atomnos,
    cprops.charge,
    cprops.mult,
    cprops.nbasis,
    cprops.atommasses,
    cprops.mosyms,
    cprops.nmo,
    cprops.atombasis,
]


class auto_combinator(combinator):
    def __init__(self, tree):
        self.name = f"Autogenerated combinator for {tree.num_nodes:} jobs"
        self.job_list = [DEFAULT_PARSERS for i in range(tree.num_nodes)]
