# Copyright (c) 2025, the cclib development team
#
# This file is part of cclib (http://cclib.github.io) and is distributed under
# the terms of the BSD 3-Clause License.
from dataclasses import dataclass

import cclib.attribute_parsers as cprops


@dataclass
class combinator:
    name: str
    job_list: list


DEFAULT_PARSERS = [
    cprops.parser_metadata,
    cprops.scfenergies,
    cprops.atomcoords,
    cprops.atomcharges,
    cprops.atomnos,
    cprops.charge,
    cprops.ccenergies,
    cprops.dispersionenergies,
    cprops.mult,
    cprops.moenergies,
    cprops.natom,
    cprops.coreelectrons,  # dependency on natom
    cprops.nbasis,
    cprops.gbasis,
    cprops.aooverlaps,
    cprops.atommasses,
    cprops.mosyms,
    cprops.mpenergies,
    cprops.moments,
    cprops.nmo,
    cprops.atombasis,
    cprops.scftargets,
    cprops.scfvalues,
    cprops.parser_metadata,
]


class auto_combinator(combinator):
    def __init__(self, tree):
        self.name = f"Autogenerated combinator for {len(tree):} jobs"
        self.job_list = [DEFAULT_PARSERS for i in range(len(tree))]
