---
name: ci

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

permissions: {}

jobs:
  prechecks:
    uses: ./.github/workflows/pre-commit.yml
  nix:
    uses: ./.github/workflows/nix.yml
  unit-tests:
    needs: [prechecks]
    uses: ./.github/workflows/test_and_package.yml
  docs:
    uses: ./.github/workflows/docs.yml
    secrets:
      CCLIB_DOCS_KEY: ${{ secrets.CCLIB_DOCS_KEY }}
  publish:
    needs: [nix, unit-tests, docs]
    uses: ./.github/workflows/publish.yml
    permissions:
      contents: write  # for making GitHub Releases
      id-token: write  # for trusted publishing and sigstore
  all:
    name: CI success
    needs: [unit-tests, publish]
    runs-on: ubuntu-24.04
    steps:
      - name: Success
        run: "true"
